# File:          Makefile
# Author:        Anton van Wezenbeek
# RCS-ID:        $Id: Makefile 76 2008-11-19 16:56:27Z anton $
# Purpose:       Makefile for gtk

LIBS=`wx-config --libs all --debug=no` -lwxextension.v2.0.gtk -lodbc
CFLAGS=`wx-config --cflags --debug=no`
PROGRAM=$(APP_VERSION).gtk

include ../../Makefile.env
