component_depth: 2

languages:
- name: cpp

  production:
    exclude:
      - /ci/.*
      - /data/.*
      - /external/.*
      - /locale/.*
      - /sample/.*
      - /src/lexers/.*
      - /test/.*
      
  test:
    include:
    - /test/.*
