# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp

compiler: gcc

branches:
    only:
        - v3.0

before_install:
    - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
    - sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0/ubuntu/ raring universe'
    - sudo apt-get update
    - sudo apt-get install -y libjbig0
    - sudo apt-get install -y liblzma5 
    - sudo apt-get install -y libwxbase3.0-0-unofficial libwxbase3.0-dev libwxgtk3.0-0-unofficial libwxgtk3.0-dev wx3.0-headers wx-common libwxbase3.0-dbg libwxgtk3.0-dbg wx3.0-i18n    
    - sudo apt-get install -y libcppunit-dev

script:
    - pushd build
    - make
    - popd
