# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp

env:
  global:
    # we need  a display for the gui tests
    - DISPLAY=":99.0"
    # take care that recently-used.xbel file can be written
    - XDG_DATA_HOME=$PWD

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
      env:
        - MATRIX_EVAL="CC=gcc-8 && CXX=g++-8"

    - os: osx
      osx_image: xcode9.2
      addons:
        apt:
          update: true
      env:
        - MATRIX_EVAL="rm /usr/local/include/c++ && brew update && brew install --force gcc && CC=gcc-8 && CXX=g++-8 && brew link --overwrite gcc && brew link cmake"

  allow_failures:
    - os: osx

git:
    depth: 1
    submodules: true

before_install:
    - eval "${MATRIX_EVAL}"

install:
    - ./ci/${TRAVIS_OS_NAME}-install.sh

before_script:
    - ./ci/${TRAVIS_OS_NAME}-before-script.sh

script:
    - mkdir build${TRAVIS_OS_NAME} && pushd build${TRAVIS_OS_NAME}
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DwxExBUILD_SP=ON -DwxExBUILD_TESTS=ON ..
    - make -j 4
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-prep; fi
    - ctest --timeout 120 -V ..
        
after_success:
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov; fi
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-coveralls; fi
