# This is the control file for Travis continuous integration system.
#
language: cpp

git:
  depth: 1
  submodules: true

env:
  global:
    # we need  a display for the gui tests
    - DISPLAY=":99.0"
    # take care that recently-used.xbel file can be written
    - XDG_DATA_HOME=$PWD

matrix:
  include:
    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-8', 'libboost-all-dev']
      env: _CC=gcc-8 _CXX=g++-8
      os: linux
      dist: bionic
      sudo: required
      services: xvfb

    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-8']
          packages: ['clang-8', 'valgrind', 'libboost-all-dev']
      env: _CC=clang-8 _CXX=clang++-8
      os: osx
      osx_image: xcode11
      sudo: required

  allow_failures:
    - os: linux
    - os: osx

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./ci/${TRAVIS_OS_NAME}-install.sh

before_script:
  - ./ci/${TRAVIS_OS_NAME}-before-script.sh

script:
  - mkdir build${TRAVIS_OS_NAME} && pushd build${TRAVIS_OS_NAME}
  - export CC="$_CC"
  - export CXX="$_CXX"
  - cmake -DCMAKE_CXX_COMPILER=${CXX} -DwexBUILD_TESTS=ON ..
#    - cmake -DCMAKE_BUILD_TYPE=Coverage -DwexBUILD_TESTS=ON ..
  - make -j 4
#    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-prep; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then ctest --timeout 120 -V .. ; fi
        
after_success:
#    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov; fi
#    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-coveralls; fi
