# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp

compiler: gcc

branches:
    only:
        - v3.0

before_install:
# we need  a display for the gui tests
    - export DISPLAY=:99.0
# take care that recently-used.xbel file can be written
    - export XDG_DATA_HOME=$PWD
    - sh -e /etc/init.d/xvfb start
    - sudo apt-key adv --fetch-keys http://repos.codelite.org/CodeLite.asc
    - sudo apt-add-repository 'deb http://repos.codelite.org/wx3.0.1/ubuntu/ precise universe'
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - sudo apt-get install g++-4.8
# first add dependencies for libwxgtk3
    - sudo apt-get install -y liblzma5 
    - sudo apt-get install -y libjbig0
    - sudo apt-get install -y libwxbase3.0-0-unofficial libwxbase3.0-dev libwxgtk3.0-0-unofficial libwxgtk3.0-dev wx3.0-headers wx-common libwxbase3.0-dbg libwxgtk3.0-dbg wx3.0-i18n    
    - sudo apt-get install -y libcppunit-dev
# coreutils needed for uniq and sort used in testing
    - sudo apt-get install -y coreutils

script:
    - sudo rm /usr/bin/g++
    - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
    - wx-config --cxx
    - g++ --version
    - pushd build
    - make
    - ./test-all.sh
    - popd
