# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp

compiler: gcc

branches:
    only:
        - v3.0

before_install:
    - sudo apt-get install -y libwxgtk-3.0
    - sudo apt-get install -y libcppunit-dev

script:
    - pushd build
    - make
    - popd
