# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
language: cpp

env:
  global:
    # we need  a display for the gui tests
    - DISPLAY=":99.0"
    # take care that recently-used.xbel file can be written
    - XDG_DATA_HOME=$PWD
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "eVY65PUeX5LiNzJCAiTVI1+Az4xBIzdTFTg/y9VVsfb2atyZDxejbIKCTMXX1noWiVm0+sUiNkqbYHkxku4Eay7KQ8xZp7F8GN6dQFdRkYPYPaEfLPeMn5C/mM+mqZ3ssSHe9HUQT8i3LcseqcYVDf3IeG1z5Sgh0NgbQLvcJr8="

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: osx
      compiler: clang++
      env: CXX=clang++
      osx_image: xcode8.3
  allow_failures:
    - os: osx

addons:
  coverity_scan:
    project:
      name: "antonvw/wxExtension"
      description: "Build submitted via Travis CI"
    notification_email: a.m.vanwezenbeek@gmail.com
    build_command_prepend: "sudo rm /usr/bin/g++; sudo ln -s /usr/bin/g++-4.9 /usr/bin/g++; mkdir build; pushd build; cmake .."
    build_command: "make -j 4"
    branch_pattern: coverity_scan
  
branches:
    only:
      - master

git:
    submodules: true

install:
    - ./ci/${TRAVIS_OS_NAME}-install.sh

before_script:
    - ./ci/${TRAVIS_OS_NAME}-before-script.sh

script:
    - mkdir build${TRAVIS_OS_NAME} && pushd build${TRAVIS_OS_NAME}
    - cmake -DCMAKE_BUILD_TYPE=Coverage -DwxExUSE_SSS=ON -DBUILD_TEST=ON ..
    - make -j 4
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-prep; fi
    - ctest --timeout 120 -V ..
        
after_success:
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov; fi
    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-coveralls; fi
