# This is the control file for Travis continuous integration system.
#
# It is used automatically for the repositories on Github if it's found in the
# root directory of the project.
sudo: required
dist: trusty

language: cpp

compiler: gcc

env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "eVY65PUeX5LiNzJCAiTVI1+Az4xBIzdTFTg/y9VVsfb2atyZDxejbIKCTMXX1noWiVm0+sUiNkqbYHkxku4Eay7KQ8xZp7F8GN6dQFdRkYPYPaEfLPeMn5C/mM+mqZ3ssSHe9HUQT8i3LcseqcYVDf3IeG1z5Sgh0NgbQLvcJr8="

addons:
  coverity_scan:
    project:
      name: "antonvw/wxExtension"
      description: "Build submitted via Travis CI"
    notification_email: a.m.vanwezenbeek@gmail.com
    build_command_prepend: "mkdir build; pushd build; cmake .."
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
  
branches:
    only:
      - master
      - coverity_scan

before_install:
    - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
    - sudo apt-get install ruby
    - gem install coveralls-lcov
    # first add dependencies for libwxgtk3
    - sudo apt-get install liblzma5 libjbig0
    - sudo apt-get install libwxgtk3.0-dev wx3.0-headers wx-common wx3.0-i18n    
    - sudo apt-get install libcppunit-dev
    # coreutils needed for uniq and sort used in testing
    - sudo apt-get install coreutils
    - sudo apt-get install unixodbc unixodbc-dev libmyodbc

before_script:
    # we need  a display for the gui tests
    - export DISPLAY=:99.0
    # take care that recently-used.xbel file can be written
    - export XDG_DATA_HOME=$PWD
    - sh -e /etc/init.d/xvfb start

script:
    - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then mkdir build && pushd build; fi
    - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then cmake -DwxExUSE_SSS=ON -DwxExUSE_OTL=ON ..; fi
    - if [ "$COVERITY_SCAN_BRANCH" != 1 ]; then make -j 4 && ctest -V ..; fi
