# This is the control file for Travis continuous integration system.
#
language: cpp

git:
  depth: 1
  submodules: true

env:
  global:
    # we need  a display for the gui tests
    - DISPLAY=":99.0"
    # take care that recently-used.xbel file can be written
    - XDG_DATA_HOME=$PWD

addons:
  apt:
    sources: &apt_sources
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty
      - llvm-toolchain-trusty-8

matrix:
  include:
    - env: COMPILER=g++-8
      compiler: gcc
      os: linux
      dist: trusty
      sudo: required
      addons:
        apt:
          packages: ["g++-8"]
          sources: *apt_sources

    - env: COMPILER=clang++-8
      compiler: clang
      os: osx
      osx_image: xcode10.2
      sudo: required
      addons: &clang8
        apt:
          packages: ["clang-8", "valgrind"]
          sources: *apt_sources

  allow_failures:
    - os: linux
    - os: osx

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./ci/${TRAVIS_OS_NAME}-install.sh

before_script:
  - ./ci/${TRAVIS_OS_NAME}-before-script.sh

script:
  - mkdir build${TRAVIS_OS_NAME} && pushd build${TRAVIS_OS_NAME}
  - cmake -DwexBUILD_TESTS=ON ..
#    - cmake -DCMAKE_BUILD_TYPE=Coverage -DwexBUILD_TESTS=ON ..
  - make -j 4
#    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-prep; fi
  - if [ "$TRAVIS_OS_NAME" != "osx" ]; then ctest --timeout 120 -V .. ; fi
        
after_success:
#    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov; fi
#    - if [ "$TRAVIS_OS_NAME" != "osx" ]; then make lcov-coveralls; fi
