# This is the control file for Travis continuous integration system.
#
language: cpp

git:
  depth: 1
  submodules: true

env:
  global:
    # we need  a display for the gui tests
    - DISPLAY=":99.0"
    # take care that recently-used.xbel file can be written
    - XDG_DATA_HOME=$PWD

matrix:
  include:
    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-9', 'libboost-all-dev']
      os: linux
      env: CC=gcc-9 CXX=g++-9
      dist: bionic
      sudo: required
      services: xvfb

    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-8']
          packages: ['clang-9, 'valgrind', 'libboost-all-dev']
      os: osx
      osx_image: xcode11.6
      sudo: required

before_install:
  - eval "${MATRIX_EVAL}"

install:
  - ./ci/$TRAVIS_OS_NAME-install.sh

before_script:
  - ./ci/$TRAVIS_OS_NAME-before-script.sh
  - if [ $TRAVIS_OS_NAME = osx ]; then . ./ci/use-clang.sh; fi

script:
  - if [ $TRAVIS_OS_NAME = osx ]; then ./ci/codespell.sh; fi
  - mkdir build && pushd build
  - cmake -DCMAKE_CXX_COMPILER=${CXX} -DCMAKE_BUILD_TYPE=Coverage -DwexBUILD_TESTS=ON ..
  - make -j 4
  - if [ $TRAVIS_OS_NAME = osx ]; then src/lib-test/core/wex-test-core; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then src/lib-test/ui/wex-test-ui -tce=wex::debug; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then src/lib-test/report/wex-test-report; fi
