# File:          Makefile
# Author:        Anton van Wezenbeek
# RCS-ID:        $Id: Makefile 30 2008-11-09 14:24:44Z anton $
# Purpose:       Makefile for gtk 

LIBRARY=$(APP_VERSION).gtk.so

include ../Makefile.env
