////////////////////////////////////////////////////////////////////////////////
// Name:      wex.h
// Purpose:   General wex include file
// Author:    Anton van Wezenbeek
// Copyright: (c) 2021 Anton van Wezenbeek
////////////////////////////////////////////////////////////////////////////////

#pragma once

#include <wex/accelerators.h>
#include <wex/address.h>
#include <wex/addressrange.h>
#include <wex/app.h>
#include <wex/art.h>
#include <wex/auto-complete.h>
#include <wex/auto-indent.h>
#include <wex/beautify.h>
#include <wex/bind.h>
#include <wex/blame.h>
#include <wex/chrono.h>
#include <wex/cmdline.h>
#include <wex/config.h>
#include <wex/core.h>
#include <wex/ctags-entry.h>
#include <wex/ctags.h>
#include <wex/debug-entry.h>
#include <wex/debug.h>
#include <wex/defs.h>
#include <wex/dialog.h>
#include <wex/dir.h>
#include <wex/ex-command.h>
#include <wex/ex-stream.h>
#include <wex/ex.h>
#include <wex/file-dialog.h>
#include <wex/file-history.h>
#include <wex/file.h>
#include <wex/frd.h>
#include <wex/grid-statistics.h>
#include <wex/grid.h>
#include <wex/hexmode.h>
#include <wex/indicator.h>
#include <wex/interruptible.h>
#include <wex/item-dialog.h>
#include <wex/item-template-dialog.h>
#include <wex/item-vector.h>
#include <wex/item.h>
#include <wex/lexer-props.h>
#include <wex/lexer.h>
#include <wex/lexers.h>
#include <wex/link.h>
#include <wex/listitem.h>
#include <wex/log.h>
#include <wex/macro-mode.h>
#include <wex/macros.h>
#include <wex/marker.h>
#include <wex/menu-command.h>
#include <wex/menu-commands.h>
#include <wex/menu-item.h>
#include <wex/menu.h>
#include <wex/menubar.h>
#include <wex/menus.h>
#include <wex/notebook.h>
#include <wex/odbc.h>
#include <wex/open-files-dialog.h>
#include <wex/path-lexer.h>
#include <wex/path.h>
#include <wex/presentation.h>
#include <wex/printing.h>
#include <wex/process.h>
#include <wex/property.h>
#include <wex/queue-thread.h>
#include <wex/regex.h>
#include <wex/shell.h>
#include <wex/sort.h>
#include <wex/stat.h>
#include <wex/statistics.h>
#include <wex/statusbar-pane.h>
#include <wex/statusbar.h>
#include <wex/stc-bind.h>
#include <wex/stc-entry-dialog.h>
#include <wex/stc-file.h>
#include <wex/stc.h>
#include <wex/stream-statistics.h>
#include <wex/stream.h>
#include <wex/style.h>
#include <wex/temp-filename.h>
#include <wex/textctrl-input.h>
#include <wex/textctrl.h>
#include <wex/tocontainer.h>
#include <wex/tokenize.h>
#include <wex/tool.h>
#include <wex/toolbar.h>
#include <wex/tostring.h>
#include <wex/type-to-value.h>
#include <wex/util.h>
#include <wex/variable.h>
#include <wex/vcs-command.h>
#include <wex/vcs-entry.h>
#include <wex/vcs.h>
#include <wex/version-dialog.h>
#include <wex/version.h>
#include <wex/vi-mode.h>
#include <wex/vi.h>

#include <wex/del/defs.h>
#include <wex/del/dirctrl.h>
#include <wex/del/frame.h>
#include <wex/del/listview-file.h>
#include <wex/del/listview.h>
