# File:          Makefile
# Author:        Anton van Wezenbeek
# Id:            $Id: Makefile 18 2008-11-08 13:50:50Z anton $
# Purpose:       Makefile for gtk 

LIBRARY=../lib/$(APP_VERSION).gtk.so

include ../Makefile.env
