# File:          Makefile
# Author:        Anton van Wezenbeek
# Purpose:       Makefile for gtk
# RCS-ID:        $Id: Makefile 50 2008-11-12 19:10:37Z anton $

LIBS=-L../../libs -lwxextension.v2.0.gtk -lwxfiletool.v2.0.gtk `wx-config --libs all` -lodbc
CFLAGS=`wx-config --cflags`
PROGRAM=$(APP_VERSION).gtk

include ../Makefile.env
