name: github-ci-msw

on: [push]

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: setup 7-Zip
        uses: milliewalky/setup-7-zip@v2
        # the 25.01 version gives boost errors: Dangerous link path was ignored
        with:
          tag: 24.07

      - name: Install boost
        uses: MarkusJx/install-boost@v2.5.0
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/MarkusJx/prebuilt-boost/blob/main/versions-manifest.json
          boost_version: 1.88.0
          platform_version: 2022

      - name: Add msbuild
        uses: microsoft/setup-msbuild@v2

      - name: Set BUILD_CONFIG
        run: echo "BUILD_CONFIG=$(ci\get-build-config.ps1)" >> "$env:GITHUB_ENV"

      - name: Configure
        shell: pwsh
        run: |
          .\build-gen.ps1 -boost_dir ${{steps.install-boost.outputs.BOOST_ROOT}} -tests -prepare -samples

      - name: Build
        working-directory: build
        run: |
          msbuild /noLogo /m /p:Configuration=$env:BUILD_CONFIG ALL_BUILD.vcxproj

      - name: Artifacts
        # see build-gen, currently a static build
        uses: actions/upload-artifact@v4
        with:
          name: wex-lib-windows
          path: |
            data/*.*
            build/**/*.lib
            build/**/setup.h
            build/**/*.exe

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        if:
          contains('
            refs/heads/develop
            refs/heads/master
          ', github.ref)
        with:
          build-config: Release
          tests-regex: co|fa|sy|da|ui|ct|vi|stc|vcs|del
          verbose: true

      - name: Run tests
        uses: threeal/ctest-action@v1.1.0
        continue-on-error: true
        if:
          contains('
            refs/heads/develop
            refs/heads/master
          ', github.ref) == false
        with:
          build-config: Debug
          tests-regex: co|fa|sy|da|ui|ct|vi|stc|vcs|del
          verbose: true
