name: github-ci-msw

on: [push]

jobs:
  build:
    # https://github.com/actions/runner-images/blob/main/images/windows/Windows2022-Readme.md
    runs-on: windows-latest

    strategy:
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.83.0

      - name: Add msbuild to enable devenv
        uses: microsoft/setup-msbuild@v2

      - name: Configure
        run: |
          mkdir build
          pushd build
          cmake -DBOOST_ROOT=${{steps.install-boost.outputs.BOOST_ROOT} -DCMAKE_BUILD_TYPE=Release -DwexBUILD_TESTS=ON ..

      - name: Build
        working-directory: build
        run: |
          devenv wex.sln /build Release

      - name: Run tests
        working-directory: build
        run: |
          ctest -C Release -V
