name: github-ci-ubuntu

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost
        with:
          # REQUIRED: Specify the required boost version
          # A list of supported versions can be found here:
          # https://github.com/actions/boost-versions/blob/main/versions-manifest.json
          boost_version: 1.83.0
          # OPTIONAL: Specify a platform version
          platform_version: 20.04

      - name: Install gtk
        run:
          sudo apt-get update -qq &&
          sudo apt-get install liblzma5 libjbig0 libgtk-3-dev

      - name: Install gcc, lcov, gdb
        run: sudo apt-get install -yq gcc-12 g++-12 lcov gdb

      - name: Install xvfb to allow headless tests
        run: sudo apt-get install xvfb

      - name: Install ninja
        run: sudo apt-get install ninja-build

      - name: Install coveralls
        run: sudo curl -L https://coveralls.io/coveralls-linux.tar.gz | tar -xz -C /usr/local/bin

      - name: Install robotframework
        run: sudo pip install robotframework

      - name: Configure
        # adding -s samples switch should result in app running,
        # but then the headless test keeps on running
        run: ./build-gen.sh -b -c -g -p -t -B ${{steps.install-boost.outputs.BOOST_ROOT}}
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
          CC: gcc-12
          CXX: g++-12

      - name: Make using ninja
        run: cd build && ninja

      - name: Headless Test
        run: cd build &&
          ninja lcov-prep &&
          xvfb-run --auto-servernum ctest -VV &&
          ninja lcov

      - name: Coveralls
        run: cd build && coveralls -r 9vV6skuIGeagBBkz5TCZNI12ezUv12gOj --format=lcov --file=src/app.run
